swarm:
  name:
    persona.url: https://localhost:8081/direccionDto
    datasources:
    jdbc-drivers:
      org.postgresql:
        driver-class-name: org.postgresql.Driver
        xa-datasource-class-name: org.postgresql.xa.PGXADataSource
        driver-module-name: org.postgresql
    data-sources:
      ExampleDS:
        driver-name: org.postgresql
        connection-url: jdbc:postgresql://localhost:5432/pd"
        user-name: postgres
        password: 1234